#PEGA TODOS OS VALORES DO MYSALARY
SELECT *
FROM mysalary
;

#FUNCAO FAZ A MEDIA
SELECT AVG(SALARY) 
FROM MYSALARY
;

#FUNCAO CONTA OS VALORES
SELECT count(SALARY)
FROM mysalary
;

#FUNCAO CONTA TODOS OS VALORES
SELECT count(*)
FROM mysalary
;

SELECT * 
FROM mysalary
;

#FUNCAO SOMA OS VALORES
SELECT 
SUM(SALARY)
FROM mysalary
;

#FUNCAO PEGA VALOR MINIMO
SELECT 
MIN(SALARY)
FROM mysalary
;

#FUNCAO PEGA VALOR MAXIMO
SELECT 
MAX(SALARY)
FROM mysalary
;

SELECT * 
FROM myorder
;

#CONCATENATNAR COM UM NUMERO RANDOMICO
SELECT ORDERNUMBER, ORDERNAME, CONCAT(ORDERNAME, ' ',RAND()) 
AS CONCATENATEDTEXT
FROM MYORDER
;

#FUNCAO QUE PEGA OS 5 CARACTERES DA ESQUERDA PARA A DIREITA
SELECT ORDERNUMBER, ORDERNAME, LEFT(ORDERNAME, 5) 
FROM MYORDER
;
#FUNCAO QUE PEGA OS 5 CARACTERES DA DIREITA PARA A ESQUERDA
SELECT ORDERNUMBER, ORDERNAME, RIGHT(ORDERNAME, 5) 
FROM MYORDER
;

##FUNCAO QUE DETERMINA ONDE FILTRAR O INICIO E QUANTOS CARACTERES DEVE PEGAR
SELECT ORDERNUMBER, ORDERNAME, SUBSTRING(ORDERNAME, 3, 5) 
FROM MYORDER
;

#LOWERCASE(TUDO MINUSCULO)
SELECT ORDERNUMBER, ORDERNAME, lower(ORDERNAME) 
FROM MYORDER
;

#UPERCASE(TUDO MAIUSCULO)
SELECT ORDERNUMBER, ORDERNAME, upper(ORDERNAME) 
FROM MYORDER
;

#FUNCAO LENGTH PARA DESCOBRIR O TAMANHO DA STRING
SELECT ORDERNUMBER, ORDERNAME, length(ORDERNAME) 
FROM MYORDER
;

#DEIXAR SOMENTE A PRIMEIRA LETRA MAISCULA E O RESTO MINUSCULO
SELECT ORDERNUMBER, ORDERNAME, concat((LEFT(ORDERNAME,1)) , LOWER(substring(ORDERNAME, 2,length(ORDERNAME))))
FROM MYORDER
;


SELECT('     MYTEXT    ');
SELECT LENGTH('     MYTEXT    ');

#REMOVER ESPAÇOS DA ESQUERDA DA STRING
SELECT ltrim('     MYTEXT    ');
#REMOVER ESPAÇOS DA DIREITA DA STRING
SELECT Rtrim('     MYTEXT    ');

#REMOVER OS ESPAÇOS DA STRING NA ESQUERDA E DIREITA
SELECT ltrim(RTRIM('     MYTEXT    '));
